lemma-osu/sklearn-raster

pyproject.toml
@grovduck I'm not 100% sure we'll end up using `dask-ml` at all, but I figured I'd get this in place to avoid surprises down the line, since having the wrong `dask-ml` breaks the Gist example.
There's an incompatibility between dask-ml<2024.3.20 and dask>=2024.3.0 due to the new [dask-expr optimization](https://github.com/dask/dask/issues/10995). This pins dask-ml for backwards compatibility.
See https://github.com/dask/dask-ml/issues/983
EDIT: CI is failing because there are no tests to run :man_facepalming:
=> Pin dask-ml for dask-expr compatibility

src/sknnr_spatial/datasets/_base.py, tests/test_datasets.py
There was a bug in `_load_rasters_to_dataset` that caused `compute` to fail with any Dask scheduler that requires pickling (anything but threads) because the file buffer used in raster loading isn't pickleable. The easy fix is just to load the file path built by `resources` rather than the file buffer.
For testing, I'm just directly checking that the dataset is pickleable. A more thorough test would be to fully compute the dataset with each scheduler to avoid any other surprise incompatibilities, but that would lead to some very slow tests as well as some complexity around setup/teardown with a `LocalCluster` (see dask/distributed#3540).
@grovduck let me know what you think about the testing here, and whether we should just bite the bullet and add in `compute` tests.
=> Fix dataset pickling

pyproject.toml, src/sknnr_spatial/__init__.py, src/sknnr_spatial/estimator.py, src/sknnr_spatial/image/__init__.py, src/sknnr_spatial/image/_base.py, src/sknnr_spatial/image/_dask_backed.py, src/sknnr_spatial/image/dataarray.py, src/sknnr_spatial/image/dataset.py, src/sknnr_spatial/image/ndarray.py, src/sknnr_spatial/types.py, src/sknnr_spatial/utils/estimator.py, src/sknnr_spatial/utils/image.py, src/sknnr_spatial/wrapper.py, tests/conftest.py, tests/image_utils.py, tests/test_images.py, tests/test_predict.py, tests/test_wrapper.py
@grovduck, I've been staring at this too long and feel like I'm getting to the point where there's probably some unnecessary complexity left over, but I'm going to start making it worse if I keep working on it! A second set of eyes would be a huge help when you have a chance!
Closes #13 and #14 by switching from a functional API for sklearn methods (currently `predict` and `kneighbors`) to a wrapper estimator. Now instead of calling those functions directly, you can wrap an existing estimator, fit it, and call the estimator's methods with image data, e.g.
```python
from sknnr import GNNRegressor
from sknnr_spatial.datasets import load_swo_ecoplot
from sknnr_spatial import wrap
X_img, X, y = load_swo_ecoplot(as_dataset=True)
est = wrap(GNNRegressor(n_neighbors=7)).fit(X, y) …
```
=> Estimator wrapper

src/sknnr_spatial/estimator.py, src/sknnr_spatial/image/_dask_backed.py, tests/test_predict.py
Closes #20 
This fix allows fitting unsupervised estimators with the assumption that they will always predict to shape (n_samples,).
Output dtype is now determined based on the `_estimator_type` attribute. This is likely a temporary solution as `_estimator_type` is [planned for deprecation](https://github.com/scikit-learn/scikit-learn/issues/28960) in favor of tags and explicit estimator type checking functions, but neither of those solutions are fully implemented yet.
=> Fix unsupervised fitting

pyproject.toml, src/sknnr_spatial/datasets/_base.py, src/sknnr_spatial/estimator.py, src/sknnr_spatial/image/_base.py, src/sknnr_spatial/image/_dask_backed.py, src/sknnr_spatial/image/ndarray.py, src/sknnr_spatial/types.py, src/sknnr_spatial/utils/estimator.py, src/sknnr_spatial/utils/image.py, tests/test_datasets.py, tests/test_predict.py
I noticed some ambiguous types being inferred in VS Code during usage, so I spent a little time trying to improve those. That basically boiled down to:
1. Using [`@overload`](https://adamj.eu/tech/2021/05/29/python-type-hints-how-to-use-overload/) to specify return types that depend on input parameters and
2. Using some [PEP 612](https://peps.python.org/pep-0612/) magic to prevent type annotations getting lost by the decorators.
To demonstrate, here are the inferred types in grey (activated with the `python.analysis.inlayHints.variableTypes` setting in VS Code) before the typing changes:
And after:
Aside from adding some code complexity, the downside of these changes that I realized too late is that PEP 612 wasn't implemented until Python 3.10, so I had to temporarily add …
=> Improve ambiguous type annotations

src/sknnr_spatial/estimator.py, src/sknnr_spatial/image/_base.py, src/sknnr_spatial/image/dataarray.py, src/sknnr_spatial/image/ndarray.py, src/sknnr_spatial/utils/image.py, tests/image_utils.py, tests/test_images.py, tests/test_predict.py
This closes #17 by 1) bypassing the `sklearn` feature name checks and 2) implementing our own feature name checks that are compatible with images. This also required reworking a large number of tests that would now throw warnings due to mismatched feature names.
This turned out to be trickier than I was hoping, so I've outlined the problem, solution, other solutions I considered, and changes made for testing below.
When an estimator is used to predict new data, `sklearn` compares the feature names that were seen during fitting with the feature names of the new data and raises warnings for missing feature names or errors for mismatched feature names. This is a useful feature as it can catch user errors, but was not compatible with our estimator wrappers which convert images with feature …
=> Implement feature name checking

src/sknnr_spatial/estimator.py, src/sknnr_spatial/image/_dask_backed.py, src/sknnr_spatial/utils/estimator.py, src/sknnr_spatial/utils/image.py, src/sknnr_spatial/utils/wrapper.py, tests/test_sknnr.py
This closes #25 and HOPEFULLY solves feature name warnings for the last time.
The previous fix for feature name warnings (#23) was to prevent fitting wrapped estimators with dataframe data, but this had an unintended side effect of breaking any functionality that depended on fitting with dataframes, like returning dataframe indexes in sknnr estimators.
I removed the array conversion to restore dataframe indexing, and added a function `suppress_feature_name_warnings` that suppresses missing feature name warnings in wrapped functions. By wrapping the functions applied by `apply_gufunc` (e.g. `predict` and `kneighbors`), we can suppress the warning when it arises at compute time, rather than during the eager call to `apply_gufunc`. We'll need to use that function any time that `sklearn` runs …
=> Fix dataframe indexing for `sknnr` estimators

pyproject.toml
Adds a `test_matrix` Hatch env for testing across Python versions (e.g. `hatch run test_matrix:all`).
Copy of lemma-osu/sknnr#76.
=> Add Hatch script for local Python matrix tests

src/sknnr_spatial/datasets/_base.py, src/sknnr_spatial/image.py, tests/image_utils.py, tests/test_datasets.py, tests/test_estimator.py, tests/test_image.py, tests/test_sknnr.py
Closes #29 by making `NDArrayImage` use shape `(band, y, x)`, which is consistent with multi-band images loaded by `rasterio` or `rioxarray`. Dataset loading and tests were updated to work with the new dimension order.
It's worth noting that internally, `_ImageChunk` still handles images in `(y, x, band)` order because `xr.apply_ufunc` always moves the core dimension (band) to the last axis. This means that `NDArrayImage` also has to transpose arrays before they go into the ufunc, and both image types need to transpose the ufunc outputs back to `(band, y, x)`.
To reduce some duplication introduced by that change, I refactored `apply_ufunc_across_bands` from the `Image` subclasses into the base class, with the type-specific functionality now handled by preprocessing and postprocessing …
=> Switch `NDArrayImage` dimension order to `(band, y, x)`

src/sklearn_raster/estimator.py, src/sklearn_raster/image.py, src/sklearn_raster/types.py, src/sklearn_raster/ufunc.py, src/sklearn_raster/utils/wrapper.py, tests/image_utils.py, tests/test_image.py
Closes #39 and closes #40.
@grovduck, I tried to detail all the changes below, but as usual for me this snowballed into a bigger PR than I was hoping. This mostly follows the changes we discussed in the issues, but I deviated in a few places once I got deeper into it (e.g. using an adjustable `ensure_min_samples` instead of just `prevent_empty_array` and adding `allow_cast` rather than always erroring for out-of-bounds NoData output values).
Just to get a quick demo of some of the new features, you can use the code snippet below and experiment with the mask threshold and different `skip_nodata` and `nodata_output` parameters:
```python
from sklearn_raster.datasets import load_swo_ecoplot
from sklearn_raster import wrap
from sknnr import GNNRegressor
X_img, X, y = …
```
=> Implement NoData skipping and other `apply` params

pyproject.toml
Closes #44.
This PR creates a new hatch environment called `tutorials` which tracks the optional `sklearn[tutorials]` dependency.  Along with `sklearn[datasets]`, the sklearn[tutorials]` dependency installs:
- ipykernel
- matplotlib
This hatch environment will be useful for running tutorials to be developed as part of this package.  As part of this PR, `ipykernel` has been removed as a dependency of the default hatch environment and instead exists as a dependency of `sklearn[tutorials]`.
=> Create new hatch shell for `sklearn-raster[tutorials]`

src/sklearn_raster/image.py, src/sklearn_raster/ufunc.py, src/sklearn_raster/utils/image.py
This closes #42 by making `UfuncSampleProcessor` (formerly `UfuncArrayProcessor`) work directly with arrays of samples, with the flattening of images to samples and unflattening of samples back to images now handled by the `image_to_samples` decorator.
I also did a little more refactoring and renaming throughout, mostly to make the `ufunc` module more clearly focused on samples rather than images. The refactoring of some of the `apply` logic into `_apply_to_all_samples` was unrelated, but hopefully makes it more clear that there are two parallel paths that branch out from `apply` with either `_apply_to_all_samples` or `_apply_to_valid_samples` (formerly `_skip_nodata_apply`) depending on the `skip_nodata` parameter.
@grovduck, since this was your good idea and you had some potential …
=> Refactor flattening

src/sklearn_raster/ufunc.py, tests/test_image.py
We use `result.shape[-1]` to get the number of features when populating a result array within `_apply_to_valid_samples` (below), but this will be incorrect if `result` is 1D because the ufunc squeezed out the feature dimension, which will happen with some single-output `predict` methods or a reducer with `keepdims=False`.
https://github.com/lemma-osu/sklearn-raster/blob/3ac85aa4f60bfe7fb8da8a03f28c63e556285e5a/src/sklearn_raster/ufunc.py#L217-L221
To fix that, we just need to "unsqueeze" the second dimension. Unfortunately `atleast_2d` doesn't take an `axis` argument and always adds the new axis at the start instead of the end, so I'm using [this weird transpose workaround](https://github.com/numpy/numpy/issues/12336#issuecomment-1982970589) that leaves 2D arrays unchanged but adds a new …
=> Fix bug with ufuncs that squeeze the feature dimension

src/sklearn_raster/estimator.py, src/sklearn_raster/image.py, src/sklearn_raster/utils/image.py, tests/image_utils.py, tests/test_estimator.py
This should close #48 by allowing wrapped methods like `predict` and `kneighbors` to support numpy and Xarray data with arbitrary dimensionality (including 1D), as long as the band/feature is the first dimension (or the variable for an `xr.Dataset`). 
@grovduck, I'm opening this as a draft since there are some design decisions to make and docstrings to update, and I'm not confident we won't turn up an edge case that breaks everything (this seemed way too easy). Do you mind testing this with your [1D example](https://github.com/lemma-osu/sklearn-raster/pull/45#issuecomment-2714575838) to make sure this works like you expect? If you use a Numpy array, you'll probably need to transpose it as a dataframe is stored (samples, features) instead of (features, samples). If you convert the …
=> Support wrapped methods with n-dimensional data

.pre-commit-config.yaml, tests/conftest.py
@grovduck pointed out that we're breaking [PT001](https://docs.astral.sh/ruff/rules/pytest-fixture-incorrect-parentheses-style/) according to recent ruff releases. This updates ruff and mypy to the latest releases and fixes that issue.
=> Update precommit hooks to latest

src/sklearn_raster/ufunc.py, src/sklearn_raster/utils/features.py, tests/test_features.py, tests/test_utils.py
Closes #53. This expands the error message when `nodata_output` doesn't fit in the array dtype returned by the ufunc to specify the detected dtype of the chosen value. For example, instead of `value nan does not fit in the array dtype float32` you'll now get `value nan (float64) does not fit in the array dtype (float32)`.
I also modified the error to provide a different suggested fix if the value and array are both floats. In that case, the error will suggest casting to a lower precision rather than choosing a different value.
Lastly, I refactored the logic of choosing the dtype for `nodata_output` into a util function so that it can be used in tests.
@grovduck, let me know what you think about the updated error message suggestions, and if they could be clearer or more explicit. Also, I …
=> Expand errors when `nodata_output` doesn't fit in the array dtype

src/sklearn_raster/estimator.py, tests/feature_utils.py, tests/test_estimator.py
Closes #47 by implementing the `predict_proba` method for wrapped classifiers. This is modified from `predict` (parameters and docstring are almost identical), with the addition of some validation and retrieving output target names/count from the estimator's [`classes_` attribute](https://scikit-learn.org/stable/glossary.html#term-classes_). In #47 I mentioned those could be stored in `FittedMetadata`, but it turns out there's no need since they're accessible from the estimator.
With a single-output classifier, `predict_proba` will return an array of shape `(n_classes, ...)` or a `Dataset` with classes as variables. Multi-output is not supported (details further down).
@grovduck, any feedback appreciated as usual! The tests aren't particularly exhaustive and I shoehorned classification …
=> Implement `predict_proba`

src/sklearn_raster/datasets/_base.py, src/sklearn_raster/estimator.py, src/sklearn_raster/features.py, src/sklearn_raster/ufunc.py, src/sklearn_raster/utils/features.py, src/sklearn_raster/utils/wrapper.py, tests/feature_utils.py, tests/test_estimator.py, tests/test_utils.py
Closes #43 by allowing users to specify different `nodata_output` values for the distance and neighbor grids returned by `kneighbors`. More generally, this enables multiple `nodata_output` values to be broadcast when an applied ufunc returns multiple arrays. This is implemented with the new `map_over_arguments` decorator that replaces `map_function_over_tuples` and `map_method_over_tuples` to support mapping over arbitrary named arguments instead of only the first or second positional argument, respectively.
From the issue:
> Once this is implemented, the default nodata_output for kneighbors should be revisited.
@grovduck, I'm currently still using `-2147483648` (the `int32` minimum) for the neighbor array and `np.nan` for the distance array, but I'm tempted to change the neighbor default …
=> Support multiple `nodata_output` values

.github/workflows/publish.yaml, CONTRIBUTING.md
See https://github.com/lemma-osu/sknnr/pull/93
I just copied the release section of the contributing guide from `sknnr` to keep them in sync.
Because we don't have a PyPI release for this project yet, Github is set up as a [pending publisher](https://docs.pypi.org/trusted-publishers/creating-a-project-through-oidc/), which should allow it to create the initial PyPI release when we push the first tag.
=> Add PyPI publish workflow

src/sklearn_raster/estimator.py, src/sklearn_raster/utils/estimator.py, src/sklearn_raster/utils/wrapper.py, tests/test_estimator.py
This closes #16 by implementing `transform` and `inverse_transform` methods for compatible estimators like `StandardScaler` and `PCA`. Example usage:
```python
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import make_pipeline
from sklearn_raster.datasets import load_swo_ecoplot
from sklearn_raster import wrap
X_img, X, y = load_swo_ecoplot(as_dataset=True)
pipeline = wrap(make_pipeline(
StandardScaler(),
PCA(n_components=3),
)).fit(X)
components = pipeline.transform(X_img)
components.pca0.plot()
reconstructed = pipeline.inverse_transform(components)
reconstructed.NBR.plot()
```
The actual method implementations are pretty simple and infer output shapes based on `get_feature_names_out` (as originally suggested by @grovduck) …
=> Implement `transform` and `inverse_transform`

src/sklearn_raster/estimator.py, tests/test_estimator.py
When you fit a transformer with unnamed features (i.e. a Numpy array) and generate a named feature array (e.g. an `xr.Dataset`), `inverse_transform` should assign sequential numeric names `[0, 1, 2 ... n_features]`, similar to `predict`. This wasn't happening because it relied on `FittedMetadata.feature_names` which stores the *input* feature names, which will be an empty array in that case to facilitate the feature name check. As a result, the output feature array will be empty:
```python
from sklearn.preprocessing import StandardScaler
from sklearn_raster.datasets import load_swo_ecoplot
from sklearn_raster import wrap
X_img, X, y = load_swo_ecoplot(as_dataset=True)
scaler = wrap(StandardScaler()).fit(X.values, y)
print(scaler.inverse_transform(scaler.transform(X_img)).data_vars)
``` …
=> Fix `inverse_transform` generating empty `xr.Dataset` when fit without feature names

src/sklearn_raster/estimator.py, src/sklearn_raster/features.py, src/sklearn_raster/utils/estimator.py, tests/test_estimator.py
Closes #63 
Previously, some wrapped methods would return integer variable names/coordinates (depending on whether you're using  `xr.Dataset` or `xr.DataArray`), which prevents serialization to NetCDF, Zarr, or GeoTIFF. This switches to descriptive string variables for all methods, and modifies the dimension names to match the coordinates for `xr.DataArray`. 
For example, `kneighbors` with an `xr.DataArray` would previously return dimension `k` with coordinates `[1, 2, ...]` and now returns dimension `neighbor` with coordinates `["neighbor0", "neighbor1", ...]`. Methods now return the following dimensions:
- `predict`: target
- `predict_proba`: class
- `kneighbors`: neighbor
- `transform`: feature
- `inverse_transform`: feature
We were also using a mix of types to store feature and target …
=> Fix unserializable names

.github/workflows/ci.yaml, src/sklearn_raster/estimator.py, src/sklearn_raster/features.py, src/sklearn_raster/utils/estimator.py, tests/feature_utils.py, tests/test_estimator.py
This refines how attrs are tracked in Xarray objects returned by spatial estimators. Specifically:
1. The attrs of the input data are no longer inherited by the output data (except for the coordinate attrs which contain the spatial reference). This avoids retaining attrs that are no longer accurate, e.g. storing the `scale_factor` or `unit` of a feature on a predicted target.
2. New metadata attrs `long_name` and `source_method` are set on the output. `long_name` is part of the CF convention for describing variable names. `source_method` is *not* a standard attr, but I thought it might be useful to track provenance by recording the estimator class and method used to produce the output, e.g. `RandomForestRegressor.predict`. These are in addition to `_FillValue` which we already set.
I also …
=> Drop inherited attrs and set metadata attrs on estimator results

src/sklearn_raster/datasets/_base.py, tests/test_datasets.py
This is an effort to include CF-compliant attributes in the SWO ecoplot example rasters when loaded as an `xr.Dataset`. Previously, the only attributes were those automatically assigned by `rioxarray`. 
@grovduck, I made an attempt to fill out attributes based on the docstring and a [supplementary table](https://figshare.com/articles/dataset/Data_Sheet_1_Mapping_with_height_and_spectral_remote_sensing_implies_that_environment_and_forest_structure_jointly_constrain_tree_community_composition_in_temperate_coniferous_forests_of_eastern_Washington_United_States_docx/21600438/1?file=38283090) from your 2022 Eastern Washington paper, but since I'm just copy/pasting your work, I'm hoping you can double-check and fix anything I got wrong.
I also had a few specific questions that I wasn't sure on: …
=> Set SWO ecoplot dataset global and variable attributes

src/sklearn_raster/features.py, src/sklearn_raster/ufunc.py, tests/test_features.py
This slightly simplifies how a missing `nodata_input` parameter is inferred from `_FillValue` attributes, based on [discussion](https://github.com/lemma-osu/sklearn-raster/pull/68#discussion_r2198937216) in #68.
Previously, a global `_FillValue`, i.e. a top-level attribute of an `xr.Dataset`, would be applied to variables *if* they did not define their own `_FillValue`. To simplify inference rules and be more consistent with CF conventions, the global attribute is now ignored; NoData is only inferred from variable-level attributes. In practice, this means there are two cases where `_FillValue` is applied as NoData (assuming `nodata_input` was not provided by the user):
- In an `xr.Dataset`, the `_FillValue` set on each variable will be assigned to that feature.
- In an `xr.DataArray`, the …
=> Simplify NoData inference

CHANGELOG.md, pyproject.toml
Closes #71 by removing `diagnostics` and `dataframe` dask extras from the required dependencies. I added `diagnostics` and `distributed` into the Hatch `tutorials` environment instead since they're helpful for development when testing local clusters. They might end up being used in `sklearn-raster[tutorials]` later, but I don't think it's worth putting them there pre-emptively.
=> Remove `dask` extra dependencies

docs/mkdocs.yml, docs/pages/guide/getting_started.md, docs/pages/guide/related_packages.md
Closes #37 by adding a documentation page that compares the features of `sklearn-raster` with other related packages. I tried to be impartial while focusing on features that would be generally relevant in a raster mapping context that `sklearn-raster` is designed to fill. My understanding of most of the other packages is based on a pretty shallow reading of their documentation and/or source code, so it's not impossible that I missed some supported features.
@grovduck, any feedback is welcome here! Let me know if you can think of other features to highlight or if anything needs clarification.
=> Document related packages

CHANGELOG.md, src/sklearn_raster/estimator.py, src/sklearn_raster/features.py, src/sklearn_raster/types.py, tests/test_features.py
I ran into some mildly surprising behavior working with an unfamiliar raster that had an incorrect `_FillValue` set, which was that values were getting masked even when I explicitly passed `nodata_input=None`. The user-provided `nodata_input` value overrides inferred values by design, but providing `None` was indistinguishable from not providing anything, which resulted in the value being inferred.
This fixes that behavior by changing the default parameter from `None` to a sentinel enum singleton `MissingType.MISSING`, allowing you to explicitly set `None` as the NoData value and effectively disable masking.
=> Allow `nodata_input=None` to override `_FillValue`

CHANGELOG.md, docs/pages/guide/raster_formats.md, src/sklearn_raster/features.py, src/sklearn_raster/types.py, tests/test_estimator.py
This adds `pd.DataFrame` as a supported feature array type, allowing estimators to predict, transform, etc. to and from dataframes. Under the hood, this is done by converting the dataframe to a 2D `xr.DataArray` (features and rows), applying the ufunc as normal, and converting it back to a dataframe. 
Unlike higher-dimensional data types, dataframes are already technically supported with `sklearn` estimators, but using a wrapped estimator offers some advantages:
1. Dataframe inputs produce dataframe outputs with a matching index and targets as column names.
2. Rows that contain NaN or encoded NoData features can be 1) skipped for performance and 2) encoded as NoData in the output.
The other immediate benefit is that if you wrap a `FeatureArrayEstimator` to work with other data types, it …
=> Add support for `pd.DataFrame` features
